"""BaseGame クラス (Phase 141 分割)

着手/捕獲/Undo/SGF出力など、エンジンや解析に依存しない
ゲーム本体の状態管理を担当する。

``katrain.core.game.Game`` はこのクラスを継承し、追加機能を委譲する形で合成する。
"""

from __future__ import annotations

import math
import os
import re
import threading
from datetime import datetime
from typing import Any

from katrain.core.constants import (
    OUTPUT_DEBUG,
    PLAYER_AI,
    PLAYER_HUMAN,
    PROGRAM_NAME,
    SGF_INTERNAL_COMMENTS_MARKER,
)
from katrain.core.engine import KataGoEngine
from katrain.core.game_node import GameNode
from katrain.core.lang import i18n, rank_label
from katrain.core.sgf_parser import SGF, Move
from katrain.core.utils import var_to_grid


class IllegalMoveException(Exception):
    pass


class KaTrainSGF(SGF):
    _NODE_CLASS = GameNode  # type: ignore[assignment]


class BaseGame:
    """Represents a game of go, including an implementation of capture rules."""

    DEFAULT_PROPERTIES = {"GM": 1, "FF": 4}

    # Class-level type annotations for instance variables
    katrain: Any
    root: GameNode
    current_node: GameNode
    game_id: str
    sgf_filename: str | None
    insert_mode: bool
    external_game: bool
    main_time_used: int
    board: list[list[int]]
    chains: list[list[Move]]
    prisoners: list[Move]
    last_capture: list[Move]

    def __init__(
        self,
        katrain: Any,
        move_tree: GameNode | None = None,
        game_properties: dict[str, Any | None] | None = None,
        sgf_filename: str | None = None,
        bypass_config: bool = False,  # if True, skip config-driven defaults (e.g. auto-undo)
    ) -> None:
        self.katrain = katrain
        self._lock = threading.RLock()  # RLock for set_current_node → _calculate_groups reentry
        self.sgf_filename = sgf_filename
        if self.sgf_filename:
            import hashlib

            self.game_id = f"sgf_{hashlib.md5(self.sgf_filename.encode()).hexdigest()[:12]}"
        else:
            self.game_id = datetime.strftime(datetime.now(), "%Y-%m-%d %H %M %S")

        self.insert_mode = False
        self.external_game = False  # not generated by katrain at some point

        if move_tree:
            self.root = move_tree
            self.external_game = PROGRAM_NAME not in self.root.get_property("AP", "")
            handicap = int(self.root.handicap)
            num_starting_moves_black = 0
            node: GameNode = self.root
            while node.children:
                child = node.children[0]
                assert isinstance(child, GameNode)
                node = child
                if node.player == "B":
                    num_starting_moves_black += 1
                else:
                    break

            if (
                handicap >= 2
                and not self.root.placements
                and num_starting_moves_black != handicap
                and not (self.root.children and self.root.children[0].placements)
            ):  # not really according to sgf, and not sure if still needed, last clause for fox
                self.root.place_handicap_stones(handicap)
        else:
            default_properties = {**BaseGame.DEFAULT_PROPERTIES, "DT": self.game_id}
            if not bypass_config:
                default_properties.update(
                    {
                        "SZ": katrain.config("game/size"),
                        "KM": katrain.config("game/komi"),
                        "RU": katrain.config("game/rules"),
                    }
                )
            merged_props: dict[str, list[Any]] = {k: [v] for k, v in default_properties.items()}
            if game_properties:
                for k, v in game_properties.items():
                    merged_props[k] = [v] if not isinstance(v, list) else v
            self.root = GameNode(properties=merged_props)
            handicap = katrain.config("game/handicap")
            if not bypass_config and handicap:
                self.root.place_handicap_stones(handicap)

        if not self.root.get_property("RU"):  # if rules missing in sgf, inherit current
            self.root.set_property("RU", katrain.config("game/rules"))

        self.set_current_node(self.root)
        self.main_time_used = 0

        # restore shortcuts
        all_nodes = [n for n in self.root.nodes_in_tree if isinstance(n, GameNode)]
        shortcut_id_to_node: dict[Any, GameNode] = {node.get_property("KTSID", None): node for node in all_nodes}
        for node in all_nodes:
            shortcut_id = node.get_property("KTSF", None)
            if shortcut_id and shortcut_id in shortcut_id_to_node:
                shortcut_id_to_node[shortcut_id].add_shortcut(node)

    # -- move tree functions --
    def _init_state(self) -> None:
        board_size_x, board_size_y = self.board_size
        self.board = [[-1 for _x in range(board_size_x)] for _y in range(board_size_y)]  # type: list[list[int]]  #  board pos -> chain id
        self.chains = []  # type: list[list[Move]]  #   chain id -> chain
        self.prisoners = []  # type: list[Move]
        self.last_capture = []  # type: list[Move]

    def _calculate_groups(self) -> None:
        with self._lock:
            self._init_state()
            try:
                for node in self.current_node.nodes_from_root:
                    for m in node.move_with_placements:
                        self._validate_move_and_update_chains(
                            m, True
                        )  # ignore ko since we didn't know if it was forced
                    if node.clear_placements:  # handle AE by playing all moves left from empty board
                        clear_coords = {c.coords for c in node.clear_placements}
                        stones = [m for c in self.chains for m in c if m.coords not in clear_coords]
                        self._init_state()
                        for m in stones:
                            self._validate_move_and_update_chains(m, True)
            except IllegalMoveException as e:
                raise Exception(f"Unexpected illegal move ({str(e)})")

    def _validate_move_and_update_chains(self, move: Move, ignore_ko: bool) -> None:
        board_size_x, board_size_y = self.board_size

        def neighbours(moves: list[Move]) -> set[int]:
            return {
                self.board[m.coords[1] + dy][m.coords[0] + dx]
                for m in moves
                if m.coords is not None
                for dy, dx in [(-1, 0), (1, 0), (0, -1), (0, 1)]
                if 0 <= m.coords[0] + dx < board_size_x and 0 <= m.coords[1] + dy < board_size_y
            }

        ko_or_snapback = len(self.last_capture) == 1 and self.last_capture[0] == move
        self.last_capture = []

        if move.is_pass:
            return

        assert move.coords is not None
        if self.board[move.coords[1]][move.coords[0]] != -1:
            raise IllegalMoveException("Space occupied")

        # merge chains connected by this move, or create a new one
        nb_chains = list({c for c in neighbours([move]) if c >= 0 and self.chains[c][0].player == move.player})
        if nb_chains:
            this_chain = nb_chains[0]
            self.board = [[nb_chains[0] if sq in nb_chains else sq for sq in line] for line in self.board]
            for oc in nb_chains[1:]:
                self.chains[nb_chains[0]] += self.chains[oc]
                self.chains[oc] = []
            self.chains[nb_chains[0]].append(move)
        else:
            this_chain = len(self.chains)
            self.chains.append([move])
        self.board[move.coords[1]][move.coords[0]] = this_chain

        # check captures
        opp_nb_chains = {c for c in neighbours([move]) if c >= 0 and self.chains[c][0].player != move.player}
        for c in opp_nb_chains:
            if -1 not in neighbours(self.chains[c]):  # no liberties
                self.last_capture += self.chains[c]
                for om in self.chains[c]:
                    assert om.coords is not None  # stones on board always have coords
                    self.board[om.coords[1]][om.coords[0]] = -1
                self.chains[c] = []
        if ko_or_snapback and len(self.last_capture) == 1 and not ignore_ko:
            raise IllegalMoveException("Ko")
        self.prisoners += self.last_capture

        # suicide: check rules and throw exception if needed
        if -1 not in neighbours(self.chains[this_chain]):
            rules = self.rules
            if len(self.chains[this_chain]) == 1:  # even in new zealand rules, single stone suicide is not allowed
                raise IllegalMoveException("Single stone suicide")
            elif (isinstance(rules, str) and rules in ["tromp-taylor", "new zealand"]) or (
                isinstance(rules, dict) and rules.get("suicide", False)
            ):
                self.last_capture += self.chains[this_chain]
                for om in self.chains[this_chain]:
                    assert om.coords is not None  # stones on board always have coords
                    self.board[om.coords[1]][om.coords[0]] = -1
                self.chains[this_chain] = []
                self.prisoners += self.last_capture
            else:  # suicide not allowed by rules
                raise IllegalMoveException("Suicide")

    # Play a Move from the current position, raise IllegalMoveException if invalid.
    def play(self, move: Move, ignore_ko: bool = False) -> GameNode:
        board_size_x, board_size_y = self.board_size
        if not move.is_pass:
            assert move.coords is not None
            if not (0 <= move.coords[0] < board_size_x and 0 <= move.coords[1] < board_size_y):
                raise IllegalMoveException(f"Move {move} outside of board coordinates")
        try:
            self._validate_move_and_update_chains(move, ignore_ko)
        except IllegalMoveException:
            self._calculate_groups()
            raise
        with self._lock:
            played_node = self.current_node.play(move)
            assert isinstance(played_node, GameNode)
            self.current_node = played_node
        return played_node

    # Insert a list of moves from root, often just adding one.
    def sync_branch(self, moves: list[Move]) -> GameNode:
        node: GameNode = self.root
        with self._lock:
            for move in moves:
                next_node = node.play(move)
                assert isinstance(next_node, GameNode)
                node = next_node
        return node

    def set_current_node(self, node: GameNode) -> None:
        self.current_node = node
        self._calculate_groups()

    def undo(self, n_times: int | str = 1, stop_on_mistake: Any = None) -> None:
        """Undo moves with thread-safe state update.

        Lock scope: state mutation only (current_node, _calculate_groups).
        UI updates are triggered separately by caller via update_state().

        Args:
            n_times: Number of moves to undo, or "branch"/"main-branch" for special modes.
            stop_on_mistake: Stop on mistake threshold (optional).
        """
        with self._lock:
            break_on_branch = False
            cn: GameNode = self.current_node
            break_on_main_branch = False
            last_branching_node = cn
            effective_n_times: int
            if n_times == "branch":
                effective_n_times = 9999
                break_on_branch = True
            elif n_times == "main-branch":
                effective_n_times = 9999
                break_on_main_branch = True
            else:
                assert isinstance(n_times, int)
                effective_n_times = n_times
            for _move in range(effective_n_times):
                if (
                    stop_on_mistake is not None
                    and cn.points_lost is not None
                    and cn.points_lost >= stop_on_mistake
                    and self.katrain.players_info[cn.player].player_type != PLAYER_AI
                ):
                    parent = cn.parent
                    if isinstance(parent, GameNode):
                        self.set_current_node(parent)
                    return
                previous_cn = cn
                if cn.shortcut_from:
                    cn = cn.shortcut_from
                elif not cn.is_root:
                    parent = cn.parent
                    if isinstance(parent, GameNode):
                        cn = parent
                    else:
                        break  # root or invalid parent
                else:
                    break  # root
                if break_on_branch and len(cn.children) > 1:
                    break
                elif break_on_main_branch and cn.ordered_children[0] != previous_cn:  # implies > 1 child
                    last_branching_node = cn
            if break_on_main_branch:
                cn = last_branching_node
            if cn is not self.current_node:
                self.set_current_node(cn)

    def redo(self, n_times: int = 1, stop_on_mistake: float | None = None) -> None:
        """Redo moves with thread-safe state update.

        Lock scope: state mutation only (current_node, _calculate_groups).
        UI updates are triggered separately by caller via update_state().
        """
        with self._lock:
            cn: GameNode = self.current_node
            for move in range(n_times):
                if cn.children:
                    child_node = cn.ordered_children[0]
                    shortcut_to = [
                        m for m, v in cn.shortcuts_to if child_node == v
                    ]  # are we about to go to a shortcut node?
                    if shortcut_to:
                        child_node = shortcut_to[0]
                    assert isinstance(child_node, GameNode)
                    cn = child_node
                if (
                    move > 0
                    and stop_on_mistake is not None
                    and cn.points_lost is not None
                    and cn.points_lost >= stop_on_mistake
                    and self.katrain.players_info[cn.player].player_type != PLAYER_AI
                ):
                    parent = cn.parent
                    if isinstance(parent, GameNode):
                        self.set_current_node(parent)
                    return
            if stop_on_mistake is None:
                self.set_current_node(cn)

    @property
    def komi(self) -> float:
        return self.root.komi

    @property
    def board_size(self) -> tuple[int, int]:
        return self.root.board_size

    @property
    def stones(self) -> list[Move]:
        with self._lock:
            return sum(self.chains, [])

    @property
    def end_result(self) -> str | None:
        if self.current_node.end_state:
            return str(self.current_node.end_state)
        if self.current_node.parent and self.current_node.is_pass and self.current_node.parent.is_pass:
            return self.manual_score or i18n._("board-game-end")
        return None

    @property
    def prisoner_count(self) -> dict[str, int]:
        # returns prisoners that are of a certain colour as {B: black stones captures, W: white stones captures}
        return {player: sum([m.player == player for m in self.prisoners]) for player in Move.PLAYERS}

    @property
    def rules(self) -> Any:
        return KataGoEngine.get_rules(self.root.ruleset)

    @property
    def manual_score(self) -> str | None:
        rules = self.rules
        parent = self.current_node.parent
        parent_ownership: list[float | None] | None = None
        if isinstance(parent, GameNode):
            parent_ownership = parent.ownership
        if (
            not self.current_node.ownership
            or str(rules).lower() not in ["jp", "japanese"]
            or not parent
            or not parent_ownership
        ):
            if not self.current_node.score:
                return None
            score = self.current_node.score
            assert score is not None
            formatted = self.current_node.format_score(round(2 * score) / 2)
            return formatted + "?" if formatted else None
        board_size_x, board_size_y = self.board_size
        current_ownership = self.current_node.ownership
        assert current_ownership is not None
        mean_ownership: list[float] = []
        for c, p in zip(current_ownership, parent_ownership, strict=False):
            if c is not None and p is not None:
                mean_ownership.append((c + p) / 2)
        ownership_grid = var_to_grid(mean_ownership, (board_size_x, board_size_y))
        stones = {m.coords: m.player for m in self.stones}
        lo_threshold = 0.15
        hi_threshold = 0.85
        max_unknown = 10
        max_dame = 4 * (board_size_x + board_size_y)

        def japanese_score_square(square: tuple[int, int], owner: float) -> float:
            player = stones.get(square)
            if (
                (player == "B" and owner > hi_threshold)
                or (player == "W" and owner < -hi_threshold)
                or abs(owner) < lo_threshold
            ):
                return 0  # dame or own stones
            if player is None and abs(owner) >= hi_threshold:
                return round(owner)  # surrounded empty intersection
            if (player == "B" and owner < -hi_threshold) or (player == "W" and owner > hi_threshold):
                return 2 * round(owner)  # captured stone
            return math.nan  # unknown!

        scored_squares = [
            japanese_score_square((x, y), ownership_grid[y][x])
            for y in range(board_size_y)
            for x in range(board_size_x)
        ]
        num_sq = {t: sum([s == t for s in scored_squares]) for t in [-2, -1, 0, 1, 2]}
        num_unkn = sum(math.isnan(s) for s in scored_squares)
        prisoners = self.prisoner_count
        score = sum([t * n for t, n in num_sq.items()]) + prisoners["W"] - prisoners["B"] - self.komi
        self.katrain.log(
            f"Manual Scoring: {num_sq} score by square with {num_unkn} unknown, {prisoners} captures, and {self.komi} komi -> score = {score}",
            OUTPUT_DEBUG,
        )
        if num_unkn > max_unknown or (num_sq[0] - len(stones)) > max_dame:
            return None
        return self.current_node.format_score(score)

    def __repr__(self) -> str:
        return (
            "\n".join("".join(self.chains[c][0].player if c >= 0 else "-" for c in line) for line in self.board)
            + f"\ncaptures: {self.prisoner_count}"
        )

    def update_root_properties(self) -> None:
        def player_name(player_info: Any) -> str:
            if player_info.name and player_info.player_type == PLAYER_HUMAN:
                return str(player_info.name)
            else:
                return f"{i18n._(player_info.player_type)} ({i18n._(player_info.player_subtype)}){SGF_INTERNAL_COMMENTS_MARKER}"

        root_properties = self.root.properties
        x_properties: dict[str, Any] = {}
        for bw in "BW":
            if not self.external_game:
                x_properties["P" + bw] = player_name(self.katrain.players_info[bw])
                player_info = self.katrain.players_info[bw]
                if player_info.player_type == PLAYER_AI:
                    x_properties[bw + "R"] = rank_label(player_info.calculated_rank)
        if "+" in str(self.end_result):
            x_properties["RE"] = self.end_result
        self.root.properties = {**root_properties, **{k: [v] for k, v in x_properties.items()}}

    def generate_filename(self) -> str:
        self.update_root_properties()
        player_names = {
            bw: re.sub(r"[\u200b\u3164'<>:\"/\\|?*]", "", self.root.get_property("P" + bw, bw)) for bw in "BW"
        }
        base_game_name = f"{PROGRAM_NAME}_{player_names['B']} vs {player_names['W']}"
        return f"{base_game_name} {self.game_id}.sgf"

    def write_sgf(self, filename: str, trainer_config: dict[str, Any | None] | None = None) -> str:
        if trainer_config is None:
            trainer_config = self.katrain.config("trainer", {})
        save_feedback = trainer_config.get("save_feedback", False)
        eval_thresholds = trainer_config["eval_thresholds"]
        save_analysis = trainer_config.get("save_analysis", False)
        save_marks = trainer_config.get("save_marks", False)
        self.update_root_properties()
        show_dots_for = {
            bw: trainer_config.get("eval_show_ai", True) or self.katrain.players_info[bw].human for bw in "BW"
        }
        sgf = self.root.sgf(
            save_comments_player=show_dots_for,
            save_comments_class=save_feedback,
            eval_thresholds=eval_thresholds,
            save_analysis=save_analysis,
            save_marks=save_marks,
        )
        self.sgf_filename = filename
        os.makedirs(os.path.dirname(filename), exist_ok=True)
        with open(filename, "w", encoding="utf-8") as f:
            f.write(sgf)
        return i18n._("sgf written").format(file_name=filename)
